### ISSUE TITLE
Unable to install and enable the plugin

### ISSUE THREAD

**Issue by nmuldoon** [everit-org/jira-worklog-query-plugin#13]
Thanks Balazs, here are the details:

1) git clone https://github.com/everit-org/jira-worklog-query-plugin
2) atlas-package creates /jira-worklog-query-plugin/itest/target/org.everit.jira.worklog.query.plugin.itest-1.2.0-SNAPSHOT.jar
4) try to install jar in 6.3.15 / 6.3.14 - no luck as per stack trace below. Error in UPM is "The add-on has been installed but cannot be enabled. Refer to the logs for more information."
5) tried installing alongside Timetracker, still no success

stack trace:

2015-03-17 14:51:09,884 UpmAsynchronousTaskManager:thread-3 INFO admin 882x1649x1 dg71op 0:0:0:0:0:0:0:1 /rest/plugins/1.0/ [atlassian.plugin.loaders.ScanningPluginLoader] No plugins found to be installed
2015-03-17 14:51:09,898 UpmAsynchronousTaskManager:thread-3 WARN admin 882x1649x1 dg71op 0:0:0:0:0:0:0:1 /rest/plugins/1.0/ [plugin.util.resource.AlternativeDirectoryResourceLoader] Resource directory , which resolves to /Users/nmuldoon/workspace/jira6/amps-standalone/target/container/tomcat7x/cargo-jira-home does not exist
2015-03-17 14:51:09,902 UpmAsynchronousTaskManager:thread-3 WARN admin 882x1649x1 dg71op 0:0:0:0:0:0:0:1 /rest/plugins/1.0/ [plugin.osgi.factory.OsgiBundlePlugin] Unable to enable plugin 'org.everit.jira.worklog.query.plugin.itest-1.2.0.SNAPSHOT'
2015-03-17 14:51:09,902 UpmAsynchronousTaskManager:thread-3 WARN admin 882x1649x1 dg71op 0:0:0:0:0:0:0:1 /rest/plugins/1.0/ [plugin.osgi.factory.OsgiBundlePlugin] Because of this exception
com.atlassian.plugin.PluginException: org.osgi.framework.BundleException: Unresolved constraint in bundle org.everit.jira.worklog.query.plugin.itest [166]: Unable to resolve 166.0: missing requirement [166.0] package; (&(package=org.slf4j)(version>=1.7.0)(!(version>=2.0.0)))
    at com.atlassian.plugin.osgi.factory.OsgiBundlePlugin.enableInternal(OsgiBundlePlugin.java:158)
    at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:309)
    at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:134)
    at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:104)
    at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:1061)
    at com.atlassian.plugin.manager.DefaultPluginManager.scanForNewPlugins(DefaultPluginManager.java:743)
    at com.atlassian.plugin.manager.DefaultPluginManager.installPlugins(DefaultPluginManager.java:644)
    at com.atlassian.jira.plugin.JiraPluginManager.installPlugins(JiraPluginManager.java:149)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.atlassian.plugin.osgi.hostcomponents.impl.DefaultComponentRegistrar$ContextClassLoaderSettingInvocationHandler.invoke(DefaultComponentRegistrar.java:129)
    at $Proxy272.installPlugins(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:58)
    at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:62)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:56)
    at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:39)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.osgi.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:59)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at $Proxy2018.installPlugins(Unknown Source)
    at com.atlassian.upm.core.install.PluginArtifactInstallerImpl$1.doInTransaction(PluginArtifactInstallerImpl.java:55)
    at com.atlassian.upm.core.install.PluginArtifactInstallerImpl$1.doInTransaction(PluginArtifactInstallerImpl.java:50)
    at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25)
    at com.atlassian.jira.DefaultHostContextAccessor.doInTransaction(DefaultHostContextAccessor.java:34)
    at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.atlassian.plugin.osgi.hostcomponents.impl.DefaultComponentRegistrar$ContextClassLoaderSettingInvocationHandler.invoke(DefaultComponentRegistrar.java:129)
    at $Proxy317.doInTransaction(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.atlassian.plugin.osgi.bridge.external.HostComponentFactoryBean$DynamicServiceInvocationHandler.invoke(HostComponentFactoryBean.java:154)
    at $Proxy317.doInTransaction(Unknown Source)
    at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21)
    at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:58)
    at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:62)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:56)
    at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:39)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.osgi.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:59)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
    at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at $Proxy1913.execute(Unknown Source)
    at com.atlassian.upm.core.install.PluginArtifactInstallerImpl.installPlugins(PluginArtifactInstallerImpl.java:49)
    at com.atlassian.upm.core.install.AbstractPluginInstallHandler.installSingleArtifact(AbstractPluginInstallHandler.java:94)
    at com.atlassian.upm.core.install.JarPluginInstallHandler.installPluginInternal(JarPluginInstallHandler.java:47)
    at com.atlassian.upm.core.install.AbstractPluginInstallHandler.installPlugin(AbstractPluginInstallHandler.java:48)
    at com.atlassian.upm.core.install.DefaultPluginInstallationService.execute(DefaultPluginInstallationService.java:111)
    at com.atlassian.upm.core.install.DefaultPluginInstallationService.install(DefaultPluginInstallationService.java:87)
    at com.atlassian.upm.install.UpmPluginInstallationService.install(UpmPluginInstallationService.java:94)
    at com.atlassian.upm.core.rest.resources.install.InstallTask.installFromFile(InstallTask.java:123)
    at com.atlassian.upm.core.rest.resources.install.InstallFromFileTask.executeTask(InstallFromFileTask.java:38)
    at com.atlassian.upm.core.rest.resources.install.InstallTask.call(InstallTask.java:60)
    at com.atlassian.upm.core.rest.resources.install.InstallTask.call(InstallTask.java:34)
    at com.atlassian.upm.core.rest.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:78)
    at com.atlassian.upm.core.rest.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:73)
    at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:42)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle org.everit.jira.worklog.query.plugin.itest [166]: Unable to resolve 166.0: missing requirement [166.0] package; (&(package=org.slf4j)(version>=1.7.0)(!(version>=2.0.0)))
    at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3409)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:1709)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:905)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:892)
    at com.atlassian.plugin.osgi.factory.OsgiBundlePlugin.enableInternal(OsgiBundlePlugin.java:146)
    ... 88 more

**Comment by balazs-zsoldos** [comment]
You have tried to install the integration tests of the plugin. Integration tests need SLF4J but the plugin itself does not need this dependency.

To use the plugin, only the jar from the _core_ submodule is necessary. You can compile it or download it from the marketplace: https://marketplace.atlassian.com/manage/plugins/org.everit.jira.worklog.query.plugin.core/versions/201305241230/details

Btw.: I realize that the version in the integration-test submodule is wrong :).

Could you please check if the plugin (core submodule of the project or the jar from the marketplace) works for you?

**Comment by nmuldoon** [comment]
Super, thank you, shall try that shortly and report back.

## 

Nicholas Muldoon
@njm | Blog | Contact

**Comment by nmuldoon** [comment]
User error, installed quickly and painlessly via Marketplace. 

Thank you.
